.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. newbit_qt test_newbit_qt
clean: FORCE
	$(MAKE) -C .. newbit_qt_clean test_newbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_newbit_qt_check
newbit-qt newbit-qt.exe: FORCE
	 $(MAKE) -C .. newbit_qt
